baseurl = "//ndbroadbent.com/"
title = "Nathan Broadbent"
copyright = "&copy; 2016 Nathan Broadbent"
languageCode = "en-us"
theme = "academic"

# Enable comments by entering your Disqus shortname
disqusShortname = "spf13"

# Enable analytics by entering your Google Analytics tracking ID
googleAnalytics = ""


[params]
  name = "Nathan Broadbent"
  role = "Software Developer"
  email = "hello@ndbroadbent.com"
  address = "Auckland, New Zealand"

  # Date format (refer to Go's date format: http://flippinggodateformat.com )
  #   Examples: "Mon, Jan 2, 2006" or "2006-01-02"
  date_format = "Mon, Jan 2, 2006"

  # Enable global LaTeX math rendering? If false, you can enable it locally on a per page basis.
  math = false

  # Enable native social sharing buttons?
  sharing = true

  # Link custom CSS and JS assets (relative to /static/css and /static/js respectively)
  custom_css = ["dark-mode.css"]
  custom_js  = ["theme-toggle.js"]

  # Biography section.
  # Section will only be displayed if `content/home/about.md` exists.
  [params.about]
    interests = [
      "Ruby on Rails",
      "Node.js",
      "Typescript",
      "React",
      "React Native",
      "Swift",
      "Go",
      "Python",
      "AWS",
      "Docker",
      "Kubernetes",
      "Convox",
    ]
    str_interests = "My Skills Include:"
    str_experience = "Work Experience:"

    [[params.about.experience]]
      company = "DocSpring"
      company_url = "https://docspring.com"
      position = "Founder, Developer"
      year = "2017-present"

    [[params.about.experience]]
      company = "Consultant"
      position = "Web, Mobile, DevOps"
      year = "2012-2019"

    [[params.about.experience]]
      company = "HDWR"
      company_url = "https://hdwr.co"
      position = "Cofounder, Developer"
      year = "2014-2017"

    [[params.about.experience]]
      company = "Crossroads Foundation"
      company_url = "https://crossroads.org.hk/"
      position = "Full-Stack Software Engineer"
      year = "2009-2011"

  # Posts section.
  # Section will only be displayed if there are posts in `content/post/`.
  [params.posts]
    count = 5
    title = "Recent Posts"
    subtitle = ""
    str_all = "More Posts"
    str_read_more = "Read more"

  # Portfolio section.
  # Section will only be displayed if there are projects in `content/project/`.
  [params.portfolio]
    title = "Portfolio"
    subtitle = ""

  # Contact section.
  [params.contact]
    enable = true
    title = "Contact"
    subtitle = ""
    autolink = true  # Automatically link email and phone?

  # Social/Academic Networking
  #
  # Icon pack "fa" includes the following social network icons:
  #   twitter, weibo, linkedin, github, facebook, pinterest, google-plus, youtube, instagram, soundcloud
  #   For email icon, use "fa" icon pack, "envelope" icon, and "mailto:your@email.com" as the link.
  #   Full list: https://fortawesome.github.io/Font-Awesome/icons/
  #
  # Icon pack "ai" includes the following academic network icons:
  #   google-scholar, arxiv, orcid, researchgate, mendeley
  #   Full list: https://jpswalsh.github.io/academicons/

  [[params.social]]
    title = "Email"
    icon = "envelope"
    icon_pack = "fa"
    link = "mailto:hello@ndbroadbent.com"

  [[params.social]]
    title = "GitHub"
    icon = "github"
    icon_pack = "fa"
    link = "//github.com/ndbroadbent"

  [[params.social]]
    title = "Twitter"
    icon = "twitter"
    icon_pack = "fa"
    link = "//twitter.com/ndbroadbent"

  [[params.social]]
    title = "LinkedIn"
    icon = "linkedin"
    icon_pack = "fa"
    link = "https://www.linkedin.com/in/ndbroadbent"

  [[params.social]]
    title = "Toptal"
    class = "toptal"
    svgPath = "toptal_logo.svg"
    link = "https://www.toptal.com/resume/nathan-broadbent"


# Navigation Links
#   The weight parameter defines the order that the links will appear in.

[[menu.main]]
  name = "Home"
  url = "#top"
  weight = 1

[[menu.main]]
  name = "Portfolio"
  url = "#portfolio"
  weight = 2

[[menu.main]]
  name = "Blog"
  url = "https://madebynathan.com"
  weight = 3

# [[menu.main]]
#   name = "Posts"
#   url = "#posts"
#   weight = 3

[[menu.main]]
  name = "Contact"
  url = "#contact"
  weight = 4
